services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - FPL_API_BASE_URL=https://fantasy.premierleague.com/api/
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  redis:
    image: redis:7-alpine

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=fpl
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

volumes:
  redis_data: